package product

import (
	"bytes"
	"errors"
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/google/uuid"
	"github.com/hamdidal/dpp-backend/internal/models"
	"github.com/hamdidal/dpp-backend/pkg/database"
	"github.com/jung-kurt/gofpdf"
	"gorm.io/gorm"
)

func GetProductPDF(c *gin.Context) {
	id, err := uuid.Parse(c.Param("id"))
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "invalid product id"})
		return
	}

	var p models.Product
	err = database.DB.Preload("Materials").Preload("CareInstructions").First(&p, "id = ?", id).Error
	if errors.Is(err, gorm.ErrRecordNotFound) {
		c.JSON(http.StatusNotFound, gin.H{"error": "product not found"})
		return
	}
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to retrieve product"})
		return
	}

	pdf := buildPassportPDF(p)

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to generate PDF"})
		return
	}

	c.Header("Content-Disposition", fmt.Sprintf(`attachment; filename="passport-%s.pdf"`, p.ID))
	c.Data(http.StatusOK, "application/pdf", buf.Bytes())
}

func buildPassportPDF(p models.Product) *gofpdf.Fpdf {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(15, 15, 15)
	pdf.AddPage()

	pageW, _ := pdf.GetPageSize()
	contentW := pageW - 30

	// ── Header ────────────────────────────────────────────────────────────────
	pdf.SetFont("Arial", "B", 20)
	pdf.SetTextColor(30, 30, 30)
	pdf.CellFormat(contentW, 10, "Digital Product Passport", "", 1, "C", false, 0, "")

	pdf.SetFont("Arial", "", 9)
	pdf.SetTextColor(100, 100, 100)
	pdf.CellFormat(contentW, 6, fmt.Sprintf("Passport ID: %s", p.ID), "", 1, "C", false, 0, "")
	pdf.Ln(6)

	pdf.SetDrawColor(200, 200, 200)
	pdf.Line(15, pdf.GetY(), pageW-15, pdf.GetY())
	pdf.Ln(6)

	// ── Basic Info ────────────────────────────────────────────────────────────
	sectionHeader(pdf, contentW, "Basic Information")

	col1, col2 := 50.0, contentW-50
	rows := [][]string{
		{"Product Name", p.Name},
		{"Brand", strOrNA(p.Brand)},
		{"Category", strOrNA(p.Category)},
	}
	for i, row := range rows {
		if i%2 == 0 {
			pdf.SetFillColor(245, 245, 245)
		} else {
			pdf.SetFillColor(255, 255, 255)
		}
		pdf.SetFont("Arial", "B", 9)
		pdf.SetTextColor(60, 60, 60)
		pdf.CellFormat(col1, 7, row[0], "1", 0, "L", true, 0, "")
		pdf.SetFont("Arial", "", 9)
		pdf.SetTextColor(30, 30, 30)
		pdf.CellFormat(col2, 7, row[1], "1", 1, "L", true, 0, "")
	}
	pdf.Ln(6)

	// ── Materials ─────────────────────────────────────────────────────────────
	sectionHeader(pdf, contentW, "Materials")

	if len(p.Materials) == 0 {
		pdf.SetFont("Arial", "I", 9)
		pdf.SetTextColor(120, 120, 120)
		pdf.CellFormat(contentW, 7, "No materials recorded.", "", 1, "L", false, 0, "")
	} else {
		colW := []float64{contentW * 0.50, contentW * 0.25, contentW * 0.25}
		tableHeader(pdf, colW, []string{"Material", "Percentage (%)", "Origin"})
		for i, m := range p.Materials {
			if i%2 == 0 {
				pdf.SetFillColor(245, 245, 245)
			} else {
				pdf.SetFillColor(255, 255, 255)
			}
			pdf.SetFont("Arial", "", 9)
			pdf.SetTextColor(30, 30, 30)
			pdf.CellFormat(colW[0], 7, m.Name, "1", 0, "L", true, 0, "")
			pdf.CellFormat(colW[1], 7, fmt.Sprintf("%.1f", m.Percentage), "1", 0, "C", true, 0, "")
			pdf.CellFormat(colW[2], 7, strOrNA(m.Origin), "1", 1, "L", true, 0, "")
		}
	}
	pdf.Ln(6)

	// ── Care Instructions ─────────────────────────────────────────────────────
	sectionHeader(pdf, contentW, "Care Instructions")

	if len(p.CareInstructions) == 0 {
		pdf.SetFont("Arial", "I", 9)
		pdf.SetTextColor(120, 120, 120)
		pdf.CellFormat(contentW, 7, "No care instructions recorded.", "", 1, "L", false, 0, "")
	} else {
		colW := []float64{contentW * 0.35, contentW * 0.65}
		tableHeader(pdf, colW, []string{"Type", "Description"})
		for i, ci := range p.CareInstructions {
			if i%2 == 0 {
				pdf.SetFillColor(245, 245, 245)
			} else {
				pdf.SetFillColor(255, 255, 255)
			}
			pdf.SetFont("Arial", "", 9)
			pdf.SetTextColor(30, 30, 30)
			pdf.CellFormat(colW[0], 7, ci.Type, "1", 0, "L", true, 0, "")
			pdf.CellFormat(colW[1], 7, strOrNA(ci.Description), "1", 1, "L", true, 0, "")
		}
	}

	// ── Footer ────────────────────────────────────────────────────────────────
	pdf.SetY(-15)
	pdf.SetFont("Arial", "I", 8)
	pdf.SetTextColor(150, 150, 150)
	pdf.CellFormat(contentW, 6, fmt.Sprintf("Generated by DPP Backend  |  %s", p.ID), "", 0, "C", false, 0, "")

	return pdf
}

func sectionHeader(pdf *gofpdf.Fpdf, w float64, title string) {
	pdf.SetFont("Arial", "B", 11)
	pdf.SetTextColor(255, 255, 255)
	pdf.SetFillColor(60, 90, 140)
	pdf.CellFormat(w, 8, "  "+title, "", 1, "L", true, 0, "")
	pdf.Ln(2)
}

func tableHeader(pdf *gofpdf.Fpdf, colWidths []float64, headers []string) {
	pdf.SetFont("Arial", "B", 9)
	pdf.SetTextColor(255, 255, 255)
	pdf.SetFillColor(100, 130, 180)
	for i, h := range headers {
		pdf.CellFormat(colWidths[i], 7, h, "1", 0, "C", true, 0, "")
	}
	pdf.Ln(-1)
}

func strOrNA(s string) string {
	if s == "" {
		return "N/A"
	}
	return s
}
